insert into LN_MSTR values('line_01', 'kicsi gys')
insert into LN_MSTR values('line_02', 'gyors')
insert into LN_MSTR values('line_03', 'nagy, lassabb')
insert into LN_MSTR values('line_04', 'közepes méret, gyors')
insert into LN_MSTR values('line_05', 'hangos')