DBCC CHECKIDENT ('user', RESEED, 0);
insert into "USER" values('admin', '2001-01-01', 'admin', '21232f297a57a5a743894a0e4a801fc3', 1)

insert into "USER" values('Rohácsi Daniella', '2002-03-24', 'rohacsi.dana@gmail.com', 'changeme', 1)
insert into "USER" values('Walaki', '2020-01-01', 'walaki@gmail.com', 'changeme', 1)
insert into "USER" values('Berényi Miklós', '1960-11-14', 'berenyi.miklos@gmail.com', 'changeme', 3)insert into "USER" (name, birth_date, email, password, post) values ('Dori Ready', '3/19/1965', 'dready0@weebly.com', 'byrlasnHJL5x', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Iggie Gerhts', '11/27/1991', 'igerhts0@jiathis.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Merv Farge', '8/10/1990', 'mfarge1@cdc.gov', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Shawna Heiton', '4/12/1996', 'sheiton2@chron.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Robbyn Jales', '6/9/1994', 'rjales3@mit.edu', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Ellen Neeves', '2/28/1965', 'eneeves4@vk.com', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Lilli Retter', '9/10/1987', 'lretter5@fastcompany.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Ethelyn Harcase', '12/19/1983', 'eharcase6@drupal.org', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Leonid Dunston', '9/23/1981', 'ldunston7@illinois.edu', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Blair Venard', '11/17/1979', 'bvenard8@sciencedaily.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Alberto Vlasin', '1/18/1974', 'avlasin9@nyu.edu', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Neils Bysouth', '8/24/1997', 'nbysoutha@auda.org.au', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Charlie Oughton', '3/25/1998', 'coughtonb@epa.gov', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Hynda Henrionot', '2/3/1982', 'hhenrionotc@un.org', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Diannne Ballinger', '4/18/1990', 'dballingerd@google.de', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Edan Conti', '1/4/1992', 'econtie@nifty.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Bendick Perks', '9/23/1968', 'bperksf@last.fm', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Hurleigh Ashfull', '11/7/1973', 'hashfullg@mozilla.org', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Simonette Loughrey', '3/6/1988', 'sloughreyh@macromedia.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Kandace Spoerl', '5/23/1999', 'kspoerli@delicious.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Raffaello Faulds', '1/29/1966', 'rfauldsj@ask.com', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Norry Reisenstein', '6/11/1973', 'nreisensteink@mail.ru', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Fancy Chasmer', '6/2/1960', 'fchasmerl@dropbox.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Grethel Prosch', '12/12/1981', 'gproschm@bloglines.com', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Donnajean Unwin', '6/11/1969', 'dunwinn@mediafire.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Corey Brazear', '3/8/1988', 'cbrazearo@usnews.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Thaddeus Gard', '8/3/1997', 'tgardp@desdev.cn', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Lorraine Crossingham', '11/18/1984', 'lcrossinghamq@tumblr.com', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Ana Coonihan', '10/11/1981', 'acoonihanr@blogger.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Nichole Redfearn', '11/2/1972', 'nredfearns@gizmodo.com', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Dulce Mosco', '3/11/1989', 'dmoscot@sourceforge.net', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Honor Westrope', '2/17/1995', 'hwestropeu@washington.edu', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Biddie Warne', '9/24/1960', 'bwarnev@ask.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Mariquilla Chamberlen', '8/19/1995', 'mchamberlenw@yale.edu', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Arleen Pound', '7/3/1963', 'apoundx@fc2.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Susie Whyte', '7/2/1993', 'swhytey@google.nl', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Olia Whistance', '11/28/1988', 'owhistancez@slideshare.net', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Rosaleen Titcumb', '6/8/1979', 'rtitcumb10@smh.com.au', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Ceciley O''Hallihane', '10/7/1999', 'cohallihane11@wikia.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Obediah Corten', '2/14/1963', 'ocorten12@rambler.ru', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Raffarty Gillson', '2/1/2000', 'rgillson13@pagesperso-orange.fr', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Sanders Nutten', '12/14/1961', 'snutten14@nyu.edu', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Reggy Cicconetti', '4/11/1979', 'rcicconetti15@businesswire.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Sibilla Menicomb', '9/5/1981', 'smenicomb16@google.pl', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Benny McCrystal', '5/14/1996', 'bmccrystal17@toplist.cz', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Rosella Fyers', '11/7/1991', 'rfyers18@gravatar.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Bunnie Stoakes', '8/14/1996', 'bstoakes19@hibu.com', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Anatollo Jaan', '7/20/1976', 'ajaan1a@bing.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Latashia Gavin', '9/26/1960', 'lgavin1b@wikispaces.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Marillin Dacombe', '7/10/1973', 'mdacombe1c@feedburner.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Hunfredo O''Hagan', '3/26/1972', 'hohagan1d@hibu.com', 'changeme', 1);
insert into "USER" (name, birth_date, email, password, post) values ('Sunshine Sibyllina', '7/15/1967', 'ssibyllina1e@ifeng.com', 'changeme', 2);
insert into "USER" (name, birth_date, email, password, post) values ('Tybalt Kobierra', '10/14/1997', 'tkobierra1f@qq.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Brandy Bolles', '4/5/1996', 'bbolles1g@ehow.com', 'changeme', 3);
insert into "USER" (name, birth_date, email, password, post) values ('Berenice Chavey', '6/7/1968', 'bchavey1h@msu.edu', 'changeme', 1);